steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/car-rental-ui/car-rental-microservices-api-gateway:latest", "./api-gateway"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/car-rental-ui/car-rental-microservices-api-gateway:latest"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/car-rental-ui/car-rental-microservices-authentication-service:latest", "./authentication-service"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/car-rental-ui/car-rental-microservices-authentication-service:latest"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/car-rental-ui/car-rental-microservices-car-service:latest", "./car-service"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/car-rental-ui/car-rental-microservices-car-service:latest"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/car-rental-ui/car-rental-microservices-configuration-service:latest", "./configuration-service"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/car-rental-ui/car-rental-microservices-configuration-service:latest"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/car-rental-ui/car-rental-microservices-currency-service:latest", "./currency-service"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/car-rental-ui/car-rental-microservices-currency-service:latest"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/car-rental-ui/car-rental-microservices-discovery-service:latest", "./discovery-service"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/car-rental-ui/car-rental-microservices-discovery-service:latest"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/car-rental-ui/car-rental-microservices-location-service:latest", "./location-service"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/car-rental-ui/car-rental-microservices-location-service:latest"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/car-rental-ui/car-rental-microservices-opening-hours-service:latest", "./opening-hours-service"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/car-rental-ui/car-rental-microservices-opening-hours-service:latest"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/car-rental-ui/car-rental-microservices-order-service:latest", "./order-service"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/car-rental-ui/car-rental-microservices-order-service:latest"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/car-rental-ui/car-rental-microservices-logstash:latest", "./logstash"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/car-rental-ui/car-rental-microservices-logstash:latest"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/car-rental-ui/car-rental-microservices-prometheus:latest", "./prometheus"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/car-rental-ui/car-rental-microservices-prometheus:latest"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/car-rental-ui/car-rental-microservices-rabbitmq:latest", "./rabbitmq"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/car-rental-ui/car-rental-microservices-rabbitmq:latest"]

  - name: 'gcr.io/car-rental-ui/helm'
    args: [ 'upgrade', '-i', 'prometheus', './prometheus/helm' ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west6-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=car-rental-v2'

  - name: 'gcr.io/car-rental-ui/helm'
    args: [ 'upgrade', '-i', 'grafana', 'bitnami/grafana' ]
    env:
      - 'HELM_REPO_URL=https://charts.bitnami.com/bitnami'
      - 'HELM_REPO_NAME=bitnami'
      - 'GF_SECURITY_ADMIN_USER=admin'
      - 'GF_SECURITY_ADMIN_PASSWORD=eFqT8cE6GAcb'
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west6-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=car-rental-v2'

  - name: 'gcr.io/car-rental-ui/helm'
    args: [ 'upgrade', '-i', 'elasticsearch', 'elastic/elasticsearch', '-f', 'elasticsearch/helm/values.yaml' ]
    env:
      - 'HELM_REPO_URL=https://helm.elastic.co'
      - 'HELM_REPO_NAME=elastic'
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west6-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=car-rental-v2'

  - name: 'gcr.io/car-rental-ui/helm'
    args: [ 'upgrade', '-i', 'kibana', 'elastic/kibana' ]
    env:
      - 'HELM_REPO_URL=https://helm.elastic.co'
      - 'HELM_REPO_NAME=elastic'
      - 'ELASTICSEARCH_URL="http://elasticsearch:9300"'
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west6-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=car-rental-v2'

  - name: 'gcr.io/car-rental-ui/helm'
    args: [ 'upgrade', '-i', 'zipkin', 'zipkin/zipkin-helm-0.1.1.tgz' ]
    env:
      - 'HELM_REPO_URL=https://financial-times.github.io/zipkin-helm/docs'
      - 'HELM_REPO_NAME=zipkin'
      - 'STORAGE_TYPE=elasticsearch'
      - 'ES_HOSTS=elasticsearch:9300'
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west6-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=car-rental-v2'

  - name: 'gcr.io/car-rental-ui/helm'
    args: [ 'upgrade', '-i', 'rabbitmq', './rabbitmq/helm' ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west6-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=car-rental-v2'

  - name: 'gcr.io/car-rental-ui/helm'
    args: [ 'upgrade', '-i', 'logstash', './logstash/helm' ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west6-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=car-rental-v2'

timeout: 1h