apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.amqp }}
      targetPort: 5672
      protocol: TCP
      name: amqp
    - port: {{ .Values.service.ports.http }}
      targetPort: 15672
      protocol: TCP
      name: http
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
