#!/usr/bin/env sh

set -e

helm install configuration-service configuration-service/helm/
helm install discovery-service discovery-service/helm/
helm install currency-service currency-service/helm/
helm install opening-hours-service opening-hours-service/helm/
helm install location-service location-service/helm/
helm install car-service car-service/helm/
helm install order-service order-service/helm/
helm install api-gateway api-gateway/helm/
