#!/usr/bin/env sh


helm repo add elastic https://helm.elastic.co
helm install elasticsearch elastic/elasticsearch -f elasticsearch/helm/values.yaml
helm install kibana elastic/kibana
helm install logstash elastic/logstash

helm repo add bitnami https://charts.bitnami.com/bitnami

kubectl apply -f rabbitmq/secret-definition.yaml
helm install rabbitmq bitnami/rabbitmq -f rabbitmq/values.yaml