apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
      - v2.se.transfer-vienna.com
      secretName: ingress-tls
  rules:
    - host: v2.se.transfer-vienna.com
      http:
        paths:
          - path: /zipkin
            pathType: ImplementationSpecific
            backend:
              service:
                name: zipkin
                port:
                  number: 9411
          - path: /prometheus
            pathType: ImplementationSpecific
            backend:
              service:
                name: prometheus-server
                port:
                  number: 80
          - path: /grafana
            pathType: ImplementationSpecific
            backend:
              service:
                name: grafana
                port:
                  number: 3000
          - path: /api/v1
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-gateway
                port:
                  number: 8079
          - path: /app
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80