apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "v2-ip"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: ''
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
            path: /
          - path: /zipkin
            pathType: Prefix
            backend:
              service:
                name: zipkin
                port:
                  number: 9411
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: prometheus-server
                port:
                  number: 80
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
          - path: /api/v1/currency
            pathType: Prefix
            backend:
              service:
                name: currency-service
                port:
                  number: 8080
          - path: /api/v1/opening-hours
            pathType: Prefix
            backend:
              service:
                name: opening-hours-service
                port:
                  number: 8081
          - path: /api/v1/location
            pathType: Prefix
            backend:
              service:
                name: location-service
                port:
                  number: 8082
          - path: /api/v1/car
            pathType: Prefix
            backend:
              service:
                name: car-service
                port:
                  number: 8083
          - path: /api/v1/auth
            pathType: Prefix
            backend:
              service:
                name: authentication-service
                port:
                  number: 8085
          - path: /api/v1/order
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 8084
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: kibana-kibana
                port:
                  number: 5601
