name: "API Gateway"

env:
  MICRO_SERVICE: api-gateway
on:
  push:
    branches: [ main ]
    paths:
      - api-gateway/**
      - .github/workflows/api-gateway.yml
jobs:
  deploy:

    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          service_account_key: ${{ secrets.GCR_KEY }}

      - run: gcloud auth configure-docker

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.MICRO_SERVICE }}
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ github.event.repository.name }}-${{ env.MICRO_SERVICE }}

#      - name: helm deploy
#        uses: koslib/helm-eks-action@master
#        env:
#          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
#        with:
#          plugins: "https://github.com/jkroepke/helm-secrets" # optional
#          command: helm upgrade ${{ env.MICRO_SERVICE }} --install --wait ${{ env.MICRO_SERVICE }}/helm
