name: "Currency Service"

env:
  MICRO_SERVICE: currency-service
on:
  push:
    branches: [ main ]
    paths:
      - ${{ env.MICRO_SERVICE}}
jobs:
  deploy:

    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/setup-gcloud@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - uses: 'docker/login-action@v1'
        with:
          registry: 'gcr.io'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.MICRO_SERVICE }}
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}-${{ env.MICRO_SERVICE }}